//
//  AEXML+RCKML.swift
//  RCKML
//
//  Created by Ryan Linn on 11/2/25.
//

import AEXML

enum XmlTags {
    static var id: String { "id" }
    static var name: String { "name" }
    static var description: String { "description" }
}

extension AEXMLElement {
    /// Getter/Setter for optional child with tag "name"
    var kmlName: String? {
        get {
            optionalXmlChild(name: XmlTags.name)?.string
        }
        set {
            if let newValue {
                addChild(name: XmlTags.name, value: newValue)
            }
        }
    }
    
    /// Getter/Setter for optional child with tag "description"
    var kmlFeatureDescription: String? {
        get {
            optionalXmlChild(name: XmlTags.description)?.string
        }
        set {
            if let newValue {
                addChild(name: XmlTags.description, value: newValue)
            }
        }
    }

    // TODO: for replacing `KMLElement.xmlAttributesWithId`
    /// Shorthand to generate an attributes dictionary for use in `self.xmlElement`,
    /// using the element's optional id as the first entry in the dictionary.
    ///
    /// - Parameter id: The optional id of this KML element.
    /// - Returns: A dictionary of `["id" : self.id]` if `self.id` exists, or an empty dictionary if it doesn't.
    convenience init<K: KmlElement>(baseFor kmlElement: K.Type, id: String?) {
        // TODO: also add name, features, children: [any KMLElement]?
        let baseAttributes = [XmlTags.id : id].compactMapValues(\.self)

        self.init(
            name: kmlElement.kmlTag,
            attributes: baseAttributes
        )
    }

    /// For use in creating KMLElement from AEXMLElement, this function is shorthand
    /// for getting a known KMLElement child from the XML element.
    ///
    /// Only call this function if the child item type is absolutely certain
    /// to be present as a child of this XML element.
    ///
    /// - Parameter type: the Swift type (implementing KmlElement protocol) of the returned child.
    /// - Throws: XML error, or any type of `KMLError`
    /// - Returns: The first child element of this XML element of the given type, formatted as type `type`.
    func requiredKmlChild<T: KmlElement>(ofType type: T.Type) throws -> T {
        let subItem = try requiredXmlChild(name: T.kmlTag)
        let item = try T(xml: subItem)
        return item
    }

    /// Shorthand for getting a known child element from AEXMLElement.
    ///
    /// Only call this function if you are certain that this XML element
    /// contains a child of the given name.
    ///
    /// - Parameter name: the name of the child tag to be returned.
    /// - Throws: XML error
    /// - Returns: The first child element of this XML element that has the given name.
    func requiredXmlChild(name: String) throws -> AEXMLElement {
        let subItem = self[name]
        if let error = subItem.error {
            throw error
        }
        return subItem
    }

    /// Shorthand for getting an optional child element from AEXMLElement, bypassing
    /// error-throwing and returning nil instead.
    ///
    /// - Parameter name: The name of the child tag to be returned.
    /// - Returns: The first XML Element with the given name, or nil if not present or any error is thrown.
    func optionalXmlChild(name: String) -> AEXMLElement? {
        let subItem = self[name]
        if subItem.error != nil {
            return nil
        }
        return subItem
    }

    /// For use in creating KMLElement from AEXMLElement, this function is shorthand
    /// for getting a possible KMLElement child from the XML element.
    ///
    /// - Parameter type: the Swift type (implementing KmlElement protocol) of the returned child.
    /// - Returns: The first child element of this XML element of the given type,
    /// formatted as type `type`, or nil if no child of that type exists.
    func optionalKmlChild<T: KmlElement>(ofType type: T.Type) -> T? {
        let subItem = self[T.kmlTag]
        if subItem.error != nil {
            return nil
        }
        return try? T(xml: subItem)
    }

    /// For use in creating KMLElement from AEXMLElement, this function is shorthand for getting
    /// all possible KMLElement children of a given type from this XMLElement.
    ///
    /// - Parameter type: The Swift type (implementing KmlElement protocol) of the returned children.
    /// - Throws: KMLErrors generated by `KmlElement.init(xml:)` calls.
    /// - Returns: An array of KMLElement type `type`
    func allKmlChildren<T: KmlElement>(ofType type: T.Type) throws -> [T] {
        let childs = try children.filter { $0.name == T.kmlTag }.compactMap { try T(xml: $0) }
        return childs
    }
}
